### PR TITLE
Revisited with new JupyterLab configuration system

### PR DESCRIPTION
**Pull request by danielballan**
The hook that I used to implement this originally in #1 have been removed, but I proposed new hooks in https://github.com/jupyterlab/jupyterlab/pull/1804 that allow this to work. From the command palette, it's usable in its current state.

The drop-down menu component is not working yet due to some confusion on my part, but that should be an easy fix.

### CODE REVIEW

**Comment by danielballan** [comment]
OK, this is ready for review/merge. It requires jupyterlab 0.17.0, which is planned to be released tomorrow.

Now that it's in a working state, should we put it on PyPI? The recommend naming pattern has changed from `*-jupyterlab` to `jupyterlab_*` (see https://github.com/dask/dask-labextension/issues/15) so we should rename the repo and the package first. Can someone with the necessary permissions do that?

**Comment by danielballan** [comment]
@rgbkrk Do you have the bandwidth to look over this?

**Comment by rgbkrk** [comment]
I can click the merge button. 😉  You'll need @blink1073 for an earnest review of the plugin setup.

**Comment by blink1073** [comment]
Looks good to me, though I don't have `JupyterHub` setup to confirm that it actually works.  :wink:

**Comment by ellisonbg** [comment]
I would rename it to `jupyterlab_...`

**Pull request merged**
